# Generated by Django 5.2 on 2025-05-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_score_userresponse_delete_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='final_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='score',
            name='trait_scores',
        ),
        migrations.AddField(
            model_name='score',
            name='trait',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
