# Generated by Django 5.2 on 2025-05-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_rename_final_score_score_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='age_group',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='gender_specific',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='profession_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='reverse_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
