# Generated by Django 5.2 on 2025-05-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_finalscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalscore',
            old_name='combined_traits',
            new_name='top_traits',
        ),
    ]
