# Generated by Django 5.2 on 2025-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_rename_combined_traits_finalscore_top_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='raw_traits',
            field=models.JSONField(default=dict),
        ),
    ]
