# Generated by Django 5.2 on 2025-09-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_subscriptionplan_usersubscription_vrsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pillar_key', models.CharField(max_length=100)),
                ('pillar_name', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('rubric', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pillar_key', models.CharField(max_length=100)),
                ('pillar_name', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('expected_tone', models.CharField(blank=True, max_length=100, null=True)),
                ('rubric', models.JSONField(default=dict)),
            ],
        ),
    ]
