# Generated by Django 5.2 on 2025-09-12 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_essayprompt_vrquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('MCQ_DONE', 'Mcq Done'), ('ESSAY_DONE', 'Essay Done'), ('VR_DONE', 'Vr Done'), ('FINALIZED', 'Finalized')], default='NOT_STARTED', max_length=20)),
                ('essay_snapshot', models.JSONField(blank=True, null=True)),
                ('vr_score', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
